// Service-role Supabase client — bypasses all RLS policies.
//
// ONLY import this in Route Handlers and Server Actions where the caller's
// admin status has already been verified. NEVER import in Client Components,
// and never in files without "use server". The service role key must never
// reach the browser.
//
// Typed with the Database interface generated by `npm run db:types`.

import { createClient as createSupabaseClient } from "@supabase/supabase-js";
import type { Database } from "@/types/supabase";

export function createAdminClient() {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!supabaseUrl || !serviceRoleKey) {
    throw new Error(
      "Missing Supabase service role environment variables. Check .env.local."
    );
  }

  return createSupabaseClient<Database>(supabaseUrl, serviceRoleKey, {
    auth: {
      autoRefreshToken: false,
      persistSession: false,
    },
  });
}
