// Browser-side Supabase client (for Client Components).
// Uses @supabase/ssr for cookie-based session management.
// Typed with the Database interface generated by `npm run db:types`.

import { createBrowserClient } from "@supabase/ssr";
import type { Database } from "@/types/supabase";

export function createClient() {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

  if (!supabaseUrl || !supabaseAnonKey) {
    throw new Error(
      "Missing Supabase environment variables. Check .env.local against .env.example."
    );
  }

  return createBrowserClient<Database>(supabaseUrl, supabaseAnonKey);
}
